In [9]:
def user_in_experiment(user_id):
    if user_id % 2 != 0:
        return True
    else:
        return False

user_in_experiment(5)
# user_id_list = [1,2,3,4,5]
# [user_in_experiment(l) for l in user_id_list]

True

In [24]:
POPULAR_RESTAURANTS = ["Laut", "Rosa Mexicano", "Ootoya", "Dig Inn"]

def get_popular_restaurants(list_of_rest):
   pop_rest = [rest for rest in list_of_rest if rest in POPULAR_RESTAURANTS] 
   return pop_res

list_of_rest = ["res_1", "Rosa Mexicano", "res_2", "Dig Inn", "res_3"]

get_popular_restaurants(list_of_rest)


['Rosa Mexicano', 'Dig Inn']

In [32]:
restaurants = [
    {
"name": "Ootoya",
        "rating":8.0
    },
    {
"name": "Chipotle",
        "rating":6.6
    },
    {
"name": "Burger & Lobster",
        "rating": 7.2
    },
    {
"name": "Laut",
        "rating": 8.1
    }
]

list_of_sorted_rest = [n["name"] for n in sorted(restaurants,key=lambda x: x["rating"],reverse=True)]
list_of_sorted_rest

['Laut', 'Ootoya', 'Burger & Lobster', 'Chipotle']

In [41]:
from scipy.optimize import minimize

orig_func = lambda x: x**2-49

func = minimize(orig_func,[1,])

func.x

array([-9.44232006e-09])

In [60]:
from scipy.optimize import minimize

orig_func = lambda x: x**2-49

min_func = minimize(orig_func,[1,])
min_func["x"]

array([-9.44232006e-09])

In [59]:
orig_func = lambda x: -(-x**2+5*x+7)
max_func = minimize(orig_func,[1,])
max_func["x"]

array([2.49999993])

In [21]:
import tensorflow as tf

a = tf.constant(5, name="input_a")
b = tf.constant(3, name="input_b")
c = tf.multiply(a,b, name="multiply_c")
d = tf.add(a,b, name="add_d")
e = tf.add(c,d, name="add_e")
sess = tf.Session()
output = sess.run(e)
writer=tf.summary.FileWriter('./my_graph_2',sess.graph)
writer.close()
sess.close()

In [38]:
tf.reset_default_graph()

In [49]:
W=tf.Variable([0.3],tf.float32)
b=tf.Variable([-0.3],tf.float32)
x=tf.placeholder(tf.float32)
linear_model = W*x+b
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)

In [52]:
print(sess.run(linear_model, {x:[1,2,3,4]}))

[0.         0.3        0.6        0.90000004]


In [148]:
W=tf.Variable([0.3],tf.float32)
b=tf.Variable([-0.3],tf.float32)
x=tf.placeholder(tf.float32)
linear_model = W*x+b
sess=tf.Session()
init=tf.global_variables_initializer()
sess.run(init)

y=tf.placeholder(tf.float32)
squared_deltas=tf.square(linear_model-y)
cost=tf.reduce_sum(squared_deltas)
print(sess.run(cost,{x:[1,2,4,5],y:[0,-1,-2,-3]}),end="\n\n")

optimizer = tf.train.GradientDescentOptimizer(0.009)
train = optimizer.minimize(cost)

a = 100
print(sess.run(cost,{x:[1,2,4,5],y:[0,-1,-2,-3]}))
print(sess.run([W,b]),end="\n\n")
for i in range(10000):
    sess.run(train, {x:[1,2,4,5],y:[0,-1,-2,-3]})
    if i==a:
        print(a,sess.run(cost,{x:[1,2,4,5],y:[0,-1,-2,-3]}),end=" ")
        a += 300
        print(sess.run([W,b]))
print(end="\n\n")
print(sess.run([W,b]))
sess.close()

57.989998

57.989998
[array([0.3], dtype=float32), array([-0.3], dtype=float32)]

100 0.21272391 [array([-0.7133569], dtype=float32), array([0.5298736], dtype=float32)]
400 0.17441937 [array([-0.7556314], dtype=float32), array([0.7201088], dtype=float32)]
700 0.17441863 [array([-0.7558131], dtype=float32), array([0.7209266], dtype=float32)]
1000 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
1300 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
1600 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
1900 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
2200 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
2500 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
2800 0.1744186 [array([-0.7558136], dtype=float32), array([0.7209286], dtype=float32)]
3100 0.1744186 [array([-0.7558136], dtype=float3